version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432" # host:container — match your Go code’s 5433
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  backend:
    build: ./backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "80:3000" # match main.go ListenAndServe
    env_file:
      - ./.env
    command: ["/app/song_randomizer"]
    working_dir: /app

volumes:
  pgdata:
